FROM node:20.17.0-alpine as base

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

FROM base as build

COPY . .

RUN yarn prisma generate

RUN yarn build

FROM base as production

ENV NODE_ENV=production

WORKDIR /app

COPY --from=build /app/package.json app/yarn.lock

RUN yarn install --production --frozen-lockfile

COPY --from=build /app/dist ./dist

COPY --from=build /app/prisma/__generated__ ./prisma/__generated__

CMD ["node", "dist/main"]